
# Site settings

url: "jonweiler.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-70039434-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

#############
# HTML Head #
#############

author: "Jon Weiler"
lang: "en"
title: "Jon Weiler"
favicon: "/img/favicon.ico"
description: "Blog and website of Jon Weiler, former U.S. Army Sniper, combat veteran with the 82nd Airborne Division, Firearm Instructor, Extreme Long Range Shooter, Adventure Race Organizer, Veteran Advocate, Husband and Father"
keywords: "Blog and website of Jon Weiler, former U.S. Army Sniper, combat veteran with the 82nd Airborne Division, Firearm Instructor, Extreme Long Range Shooter, Adventure Race Organizer, Veteran Advocate, Husband and Father"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The mind quits long before the body."
  - text: "See possibile impossibilities."
  - text: "I can.  I will."
  - text: "Lead by Example."


########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
pinterest-share: True
vkontakte-share: false
disqus-shortname: "jonweiler"

###############
# Life Events #
###############

events:
  - image: "/img/career/st.png"
    date: "November 2, 2015"
    description: "Survival Trial goes into 5th year of adventure races"
  - image: "/img/career/wu.png"
    date: "November 2, 2015"
    description: "Whittington U Schedules 5th year of Courses"
  - image: "/img/career/pmi.png"
    date: "September 2015"
    description: "PMI begins Mobile Training Course initiative"
  - image: "/img/career/wu.png"
    date: "2012-2013"
    description: "Range Construction and Writing Curriculum"
  - image: "/img/career/wr.png"
    date: "2012"
    description: "Created the Warrior Rendezvous"
  - image: "/img/career/wu.png"
    date: "2011"
    description: "Began building the Whittington U"
  - image: "/img/career/st.png"
    date: "September 11, 2011"
    description: "Pioneered concept of Survival Trial"
  - image: "/img/career/hi.png"
    date: "2010"
    description: "Featured on Sniper Bulletproof (History)"	
  - image: "/img/career/hi.png"
    date: "2009"
    description: "Featured on High Impact M16 (History)"
  - image: "/img/career/pmi.png"
    date: "2008"
    description: "Build Training Facility in SD (failed)"
  - image: "/img/career/pmi.png"
    date: "September 11, 2007"
    description: "Incorporate Professional Marksmen Inc."
  - image: "/img/career/di.png"
    date: "2006"
    description: "Featured on Futureweapons - 2nd episode (Discovery)"
  - image: "/img/career/di.png"
    date: "2005"
    description: "Featured on Futureweapons (Discovery)"
  - image: "/img/career/50.png"
    date: "December, 2004"
    description: "Training Manager: Barrett Firearms Manufacturing, Inc."	
  - image: "/img/career/82.png"
    date: "February 14, 2003"
    description: "Deploy for OIF I"			
# First image of the Career timeline
career-img: "/img/career/default.png"


##################
# Contact layout #
##################

email: "jonw@survivaltrial.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://www.facebook.com/jon.weiler"
  - title: "twitter"
    url: "https://twitter.com/weilerjon"
  - title: "youtube"
    url: "https://www.youtube.com/channel/UC7JvS06KFwBGFnrkjp_QKew"
  - title: "instagram"
    url: "https://instagram.com/jon_weiler"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems: [jekyll-paginate]
